In [1]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [2]:
type(my_list)

list

In [5]:
import numpy as np

In [9]:
arr = np.array(my_list)

In [10]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(3.0)

array([0., 1., 2.])

In [14]:
np.arange(20,10)

array([], dtype=int64)

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [18]:
np.arange(10,10)

array([], dtype=int64)

In [19]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
rand(3,2)

NameError: name 'rand' is not defined

In [27]:
random.rand(3,2)

NameError: name 'random' is not defined

In [28]:
np.random.rand(3,2)

array([[0.52028753, 0.22883308],
       [0.13856199, 0.19456109],
       [0.588315  , 0.59106111]])

In [29]:
np.random.randint(2,4)

2